# Generated by Django 4.1.7 on 2023-03-15 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bedarf", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BedarVZP",
            new_name="BedarfVZP",
        ),
    ]
